source: .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md']
keep_files:  ['.git', '.svn']

# github overrides some values as follows
safe: true
lsi: false
pygments: true


baseurl: http://alexlib.github.com/openptv.github.com/


redcloth:
  hard_breaks: false